# Generated by Django 4.1 on 2022-08-09 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Papers', '0004_alter_page_options_page_status_alter_page_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Papers.page')),
            ],
            options={
                'verbose_name_plural': 'pages',
                'ordering': ['-date_added'],
            },
            bases=('Papers.page',),
        ),
    ]
