# Generated by Django 4.1 on 2022-08-09 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Papers', '0005_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_added'], 'verbose_name_plural': 'Posts'},
        ),
    ]
