# Generated by Django 4.1 on 2022-08-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Papers', '0008_rename_type_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['-date_added'],
            },
        ),
    ]
