# Generated by Django 4.1 on 2022-08-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Papers', '0012_alter_post_options_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
