# Generated by Django 4.1 on 2022-08-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Papers', '0013_category_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
