# Generated by Django 4.1 on 2022-08-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Papers', '0015_alter_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='abstract',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
